//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalystApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balances()
        {
            this.BonusBalance = new HashSet<BonusBalance>();
        }
    
        public int id_balance { get; set; }
        public int User_id { get; set; }
        public decimal Value { get; set; }
        public Nullable<bool> BunusCard { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusBalance> BonusBalance { get; set; }
    }
}
