//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalystApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPM
    {
        public int id_userPM { get; set; }
        public int User_id { get; set; }
        public int ProductMaker_id { get; set; }
        public bool IsBlock { get; set; }
    
        public virtual ProductMakers ProductMakers { get; set; }
        public virtual Users Users { get; set; }
    }
}
