//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliviEntities : DbContext
    {
        public DeliviEntities()
            : base("name=DeliviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appeal> Appeal { get; set; }
        public virtual DbSet<Balances> Balances { get; set; }
        public virtual DbSet<BonusBalance> BonusBalance { get; set; }
        public virtual DbSet<OrdersProduct> OrdersProduct { get; set; }
        public virtual DbSet<Ordsers> Ordsers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusOP> StatusOP { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<TypeAppeal> TypeAppeal { get; set; }
        public virtual DbSet<UsersPM> UsersPM { get; set; }
        public virtual DbSet<SplashText> SplashText { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ProductMakers> ProductMakers { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
    }
}
