//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersProduct
    {
        public int id_OP { get; set; }
        public int Product_id { get; set; }
        public int Orders_id { get; set; }
        public int StatusOP_id { get; set; }
    
        public virtual Ordsers Ordsers { get; set; }
        public virtual Products Products { get; set; }
        public virtual StatusOP StatusOP { get; set; }
    }
}
