//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrdersProduct = new HashSet<OrdersProduct>();
        }
    
        public int Id_prod { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public decimal Price { get; set; }
        public int ProductMaket_id { get; set; }
        public bool IsBlock { get; set; }
        public int Category_id { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersProduct> OrdersProduct { get; set; }
        public virtual ProductMakers ProductMakers { get; set; }
    }
}
